language: android
jdk: oraclejdk7
env:
 global:
 - ANDROID_TARGET=android-15
 - ANDROID_ABI=armeabi-v7a
notifications:
 slack: androidgigigo:iqpT5BG5SCI5HgECBCdqK0zt#integrations
android:
 components:
   - tools
   - platform-tools
   - build-tools-23.0.1
   - android-23
   - extra-android-support
   - extra-google-m2repository
   - sys-img-armeabi-v7a-android-19
   - extra-android-m2repository

before_install:
  - pip install --user codecov

script:
 - gradlew check

